name: ci

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6

      - name: Set node version to 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'pnpm'

      - run: pnpm install

      - name: Run unit tests
        run: pnpm run ci

      - name: Generate coverage badge
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
